version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    container_name: web
    ports:
      - '3000:8080'
    command: npm run dev
